###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-panda-shop-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

swagger:
  base-package: com.panda.shop.weixin.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由【极客-李太白】所有，未经过允许的情况下，私自分享视频和源码属于违法行为。
  version: 1.1
  terms-of-service-url: github.com/Litaibai-Geek
  contact:
    name: 极客-李太白
    email: 552405278@qq.com